version: "3.5"

services:
  # web-client:
  #   build: ./web-client
  #   env_file: ./.env
  #   image: elize/web-client:1.0
  #   container_name: web-client
  #   ports:
  #     - 5000:80
  #   volumes:
  #     - ./web-client/build:/usr/share/nginx/html
  #     - ./web-client/nginx.conf:/etc/nginx/conf.d/default.conf

  service.event-bus:
    build: ./service.event-bus
    image: ichealthhack19/service.event-bus:1.0
    container_name: service.event-bus
    ports:
      - 5001:80
    volumes:
      - ./service.event-bus:/usr/src/app
      - /usr/src/app/node_modules

  service.cloud-stream:
    build: ./service.cloud-stream
    image: ichealthhack19/service.cloud-stream:1.0
    container_name: service.cloud-stream
    ports:
      - 5002:80
    volumes:
      - ./service.cloud-stream:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/ichealthhack19-2db1f39ff65b.json

  redis-server:
    image: redis:alpine
    container_name: redis-server
    ports:
      - 6379:6379
